import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 18,
        backgroundColor: '#f8f9fa',
    },
    titulo: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#222',
        alignSelf: 'center',
    },
    resumenRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 16,
        gap: 10,
    },
    controls: {
        marginBottom: 14,
        gap: 8,
    },
    input: {
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 11,
        fontSize: 16,
        backgroundColor: '#fff',
    },
    filtersRow: {
        flexDirection: 'row',
        gap: 8,
        alignItems: 'center',
        flexWrap: 'wrap',
        marginTop: 6,
    },
    seccionLabel: {
        fontSize: 19,
        fontWeight: 'bold',
        marginVertical: 10,
        color: '#222',
    },
    gridGroup: {
        marginRight: 26,
    },
    gridTitulo: {
        fontSize: 15,
        fontWeight: '600',
        marginBottom: 6,
        color: '#444',
        alignSelf: 'center',
    },
    gridResponsive: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        minWidth: 200,
        maxWidth: 320,
        justifyContent: 'flex-start',
    },
    tablaHeader: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
        paddingVertical: 4,
        alignItems: 'center',
        minWidth: 570,
    },
    tablaHeaderText: {
        fontSize: 16,
        fontWeight: 'bold',
        width: 80,
        textAlign: 'left',
        color: '#444',
        minWidth: 70,
        maxWidth: 120,
    },
    tablaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        borderBottomWidth: 0.5,
        borderBottomColor: '#eee',
        paddingVertical: 6,
        backgroundColor: '#fff',
        borderRadius: 6,
        marginBottom: 2,
        minWidth: 570,
    },
    tablaCell: {
        fontSize: 15,
        color: '#222',
        width: 80,
        minWidth: 70,
        maxWidth: 120,
    },
    salidaBtn: {
        backgroundColor: '#e74c3c',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    salidaBtnTxt: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
    },
    ingresoBtn: {
        backgroundColor: '#2980b9',
        paddingVertical: 13,
        borderRadius: 12,
        alignItems: 'center',
        flex: 1,
        marginRight: 9,
    },
    reservaBtn: {
        backgroundColor: '#8e44ad',
        paddingVertical: 13,
        borderRadius: 12,
        alignItems: 'center',
        flex: 1,
    },
    actionRow: {
        flexDirection: 'row',
        gap: 9,
        marginBottom: 86,
    },
    botonEdit: {
        backgroundColor: '#222',
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: 'center',
        position: 'absolute',
        bottom: 24,
        left: 18,
        right: 18,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.22,
        shadowRadius: 2.22,
        elevation: 4,
    },
    botonTexto: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 17,
    },
    chip: {
        borderWidth: 1,
        borderColor: '#bbb',
        borderRadius: 18,
        paddingHorizontal: 13,
        paddingVertical: 7,
        backgroundColor: '#fafafa',
    },
    chipActive: {
        backgroundColor: '#2c3e50',
        borderColor: '#2c3e50',
    },
    chipTxt: { color: '#333' },
    chipTxtActive: { color: '#fff', fontWeight: '600' },
    modalBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.28)',
        justifyContent: 'center',
        padding: 16,
    },
    modalCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 18,
        gap: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 8,
        elevation: 6,
    },
    modalTitulo: { fontSize: 19, fontWeight: 'bold', marginBottom: 8, color: '#2980b9' },
    seleccionTitulo: { fontSize: 14, color: '#444', marginTop: 6 },
    modalActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 14,
        marginTop: 16,
    },
    cancelBtn: { paddingHorizontal: 14, paddingVertical: 9 },
    okBtn: {
        backgroundColor: '#27ae60',
        paddingHorizontal: 14,
        paddingVertical: 9,
        borderRadius: 10,
    },
});

export default styles;